version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/nodejs-app
  - source: /client/build
    destination: /var/www/html
  - source: /nginx
    destination: /etc/nginx/sites-available/
hooks:
  BeforeInstall:
    - location: server/scripts/install_dependencies.sh # <-- CORRECTED PATH
      timeout: 300
      runas: root
  AfterInstall:
    - location: server/scripts/start_application.sh    # <-- CORRECTED PATH
      timeout: 300
      runas: root
  ApplicationStop:
    - location: server/scripts/stop_application.sh     # <-- CORRECTED PATH
      timeout: 60
      runas: root