version: 0.0
os: linux
files:
  - source: / # This means "the root of the deployment bundle"
    destination: /var/www/nodejs-app
  - source: /client/build
    destination: /var/www/html
  - source: /nginx
    destination: /etc/nginx/sites-available/
hooks:
  BeforeInstall:
    - location: server/scripts/install_dependencies.sh # Path relative to the bundle root
      timeout: 300
      runas: root
  AfterInstall:
    - location: server/scripts/start_application.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 60
      runas: root