version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Ensure this matches your required Node version
    commands:
      - echo "Installing dependencies..."
      - cd client
      - npm install --f # Install client dependencies
      - npm run build  # Build the client app
      - cd ..  # Return to root directory

      - cd server
      - npm install --f  # Install server dependencies
     
      - cd ..  # Return to root directory

  build:
    commands:
      - echo "Build phase completed successfully!"

  post_build:
    commands:
      - echo "------------------- Deploying Client to S3 -------------------"
      - aws s3 sync client/build/ s3://wildrexpipelinetesting54321/client/ --delete
      - echo "Client deployed to S3!"

      - echo "------------------- Deploying Server to EC2 via CodeDeploy -------------------"
      - aws deploy push --application-name Code-DeployApp- --s3-location s3://wildrexpipelinetesting54321/server/Code-DeployApp-.zip --description "Deploy Server Code" --region ap-southeast-1
      - echo "Server deployed to EC2!"

artifacts:
  files:
    - 'client/build/**/*'
    - 'server/build/**/*'
  base-directory: '.'  # Adjust if you want to collect more specific artifacts (e.g., server folder)
