version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - cd client && npm install # Install React dependencies
      - cd ../server && npm install # Install Node.js backend dependencies

  build:
    commands:
      - echo Building React App...
      - cd client && npm run build # Build React frontend
      - echo Building Backend...
      - cd ../server && npm run build # Build Node.js backend (if needed)

artifacts:
  files:
    - '**/*'
    - '!**/node_modules/**/*'
    - 'client/build/**/*'   # Include the React build folder
    - 'server/**/*'         # Include the backend code
