version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      # Build Client
      - echo "Building Client"
      - cd client
      - npm install
      - npm run build

      # Build Server
      - echo "Building Server"
      - cd ../server
      - npm install
      - npm run build

artifacts:
  files:
    # Include everything from the client and server build directories
    - '**/*'
  base-directory: 'server/build'  # Change this to where your server output is located
