version: 0.2

phases:
  install:
    commands:
      - echo "Installing frontend dependencies..."
      - cd client
      - npm install
      - echo "Installing backend dependencies..."
      - cd ../server
      - npm install
      - cd ..

  build:
    commands:
      - echo "Building React frontend..."
      - cd client
      - npm run build
      - echo "Building Node.js backend (if any transpilation needed)..."
      - cd ../server
      - cd ..

  post_build:
    commands:
      - echo "Running frontend tests (optional)..."
      - cd client && npm test || true
      - echo "Running backend tests (optional)..."
      - cd ../server && npm test || true
      - cd ..

artifacts:
  files:
    - 'client/build/**/*'
    - 'server/**/*'
    - 'nginx/**/*'
  base-directory: .
  discard-paths: no